# Generated by Django 3.0.6 on 2020-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empinsert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
